on:
  push:

name: Static code analysis

jobs:
  sonarcloud:
    name: SonarCloud Scan
    uses: ./.github/workflows/template-sonarcloud-scan.yml
    secrets: inherit
    with:
      enabled: true
      organization: kylelee24
      projectKey: kylelee24_bedrock-claude-chat
      logLevel: INFO
      failOnError: true
