############################################
# TEMPLATE - SonarCloud Scan
############################################

name: Test API

on:
  workflow_call:
    inputs:
      enabled:
        default: true
        required: false
        type: boolean
      runsOn:
        default: 'ubuntu-latest'
        required: false
        type: string
      organization: 
        required: true
        type: string
      projectKey:
        required: true
        type: string
      logLevel:
        default: 'INFO'
        required: false
        type: string
      failOnError:
        default: true
        required: false
        type: boolean
      # TODO: tests with conditional to only run if paths are set
      # -Dsonar.tests=./backend/tests

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ inputs.organization }}
            -Dsonar.projectKey=${{ inputs.projectKey }}
            -Dsonar.log.level=${{ inputs.logLevel }}
            -Dsonar.qualitygate.wait=${{ inputs.failOnError }}
